"""Create and optionally execute a pinned LWE-estimator transcript for CKKS.

The script extracts the *actual* coefficient-modulus primes produced by the
Microsoft SEAL API used by the prototype.  It then emits a self-contained Sage
input for malb/lattice-estimator and, when requested, runs that input in a
pinned Sage container.  Raw stdout/stderr and hashes are retained alongside a
machine-readable parameter record.

The estimator models the underlying (R)LWE sample as dimension-n LWE.  Galois
keys are key-dependent evaluation keys and rely on the usual circular/KDM
security assumption; that assumption is explicitly outside what a numerical
LWE estimator can validate.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import platform
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

import tenseal as ts
from tenseal import sealapi as sa


SCHEMA = "ckks_lwe_security_transcript.v1"
EXPECTED_ESTIMATOR_COMMIT = "3e48ef421ec256afddb3e7d2249a77eab6e9ba12"
SEAL_VERSION = "4.1.1"
SEAL_SOURCE_COMMIT = "206648d0e4634e5c61dcf9370676630268290b59"


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git_commit(path: Path) -> str:
    completed = subprocess.run(
        ["git", "-C", str(path), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip()


def extract_parameters() -> dict[str, Any]:
    degree = 8192
    bit_sizes = [60, 40, 60]
    moduli = sa.CoeffModulus.Create(degree, bit_sizes)
    primes = [int(value.value()) for value in moduli]
    observed_bits = [int(value.bit_count()) for value in moduli]
    q = math.prod(primes)
    max_128 = int(sa.CoeffModulus.MaxBitCount(degree, sa.SEC_LEVEL_TYPE.TC128))
    return {
        "scheme": "CKKS",
        "poly_modulus_degree": degree,
        "slot_count": degree // 2,
        "coeff_mod_bit_sizes_requested": bit_sizes,
        "coeff_mod_bit_sizes_observed": observed_bits,
        "coeff_modulus_primes": primes,
        "coeff_modulus_product_q": str(q),
        "log2_q": math.log2(q),
        "total_coeff_modulus_bits": sum(observed_bits),
        "first_data_level_bits": 100,
        "last_data_level_bits": 60,
        "global_scale": str(2**40),
        "scale_bits": 40,
        "seal_tc128_max_coeff_modulus_bits": max_128,
        "seal_tc128_headroom_bits": max_128 - sum(observed_bits),
        "secret_distribution": {
            "estimator": "ND.Uniform(-1, 1, n)",
            "implementation": "independent uniform ternary coefficients {-1,0,1}",
            "source": "Microsoft SEAL 4.1.1 util/rlwe.cpp sample_poly_ternary",
        },
        "error_distribution": {
            "estimator_primary": "ND.CenteredBinomial(21, n)",
            "implementation": (
                "difference of two Hamming weights, 21 independent bits per side"
            ),
            "exact_standard_deviation": math.sqrt(21 / 2),
            "seal_nominal_standard_deviation": 3.2,
            "support": [-21, 21],
            "sensitivity_model": "ND.DiscreteGaussian(3.2, n)",
            "source": "Microsoft SEAL 4.1.1 util/rlwe.cpp sample_poly_cbd",
        },
        "sample_model": {
            "m": "infinity",
            "rationale": (
                "unbounded-sample LWE sensitivity bound; conservative numerical "
                "model for public/evaluation material"
            ),
        },
        "evaluation_keys": {
            "prototype": "public key plus limited Galois keys; no relinearization keys",
            "rotation_steps_for_d672": [1, 2, 4, 8, 16, 32, 64, 128, 256, 512],
            "assumption": (
                "standard key-switching/circular (KDM) security assumption for "
                "encryptions of automorphisms of the secret key"
            ),
            "estimator_limitation": (
                "malb/lattice-estimator estimates LWE attacks but does not prove "
                "the circular/KDM assumption or circuit privacy"
            ),
        },
    }


def sage_program(parameters: dict[str, Any], profile: str) -> str:
    q = parameters["coeff_modulus_product_q"]
    estimate_call = (
        "LWE.estimate.rough(params)"
        if profile == "rough"
        else "LWE.estimate(params, jobs=1)"
    )
    return f'''# Auto-generated by system/ckks_security_transcript.py
# Estimator commit: {EXPECTED_ESTIMATOR_COMMIT}
from estimator import *
from sage.all import oo

n = 8192
q = Integer({q})
models = [
    ("seal_exact_cbd21", ND.CenteredBinomial(21, n=n)),
    ("sigma_3_2_sensitivity", ND.DiscreteGaussian(3.2, n=n)),
]

print("TRANSCRIPT_SCHEMA ckks_lwe_security_transcript.raw.v1", flush=True)
print("ESTIMATOR_COMMIT {EXPECTED_ESTIMATOR_COMMIT}", flush=True)
print("PROFILE {profile}", flush=True)
print("N", n, flush=True)
print("Q", q, flush=True)
print("LOG2_Q", RR(log(q, 2)), flush=True)
print("XS", ND.Uniform(-1, 1, n=n), flush=True)
print("M", oo, flush=True)
for model_name, error_distribution in models:
    print("MODEL_BEGIN", model_name, flush=True)
    params = LWE.Parameters(
        n=n,
        q=q,
        Xs=ND.Uniform(-1, 1, n=n),
        Xe=error_distribution,
        m=oo,
        tag="SEAL CKKS N8192 q[60,40,60] " + model_name,
    )
    print("PARAMETERS", params, flush=True)
    costs = {estimate_call}
    for attack_name in sorted(costs):
        print("ATTACK", attack_name, "::", costs[attack_name], flush=True)
    print("MODEL_END", model_name, flush=True)
print("TRANSCRIPT_END", flush=True)
'''


def docker_image_metadata(image: str) -> dict[str, Any]:
    completed = subprocess.run(
        ["docker", "image", "inspect", image, "--format", "{{json .}}"],
        check=True,
        capture_output=True,
        text=True,
    )
    inspected = json.loads(completed.stdout)
    return {
        "reference": image,
        "id": inspected.get("Id"),
        "repo_digests": inspected.get("RepoDigests", []),
        "created": inspected.get("Created"),
        "architecture": inspected.get("Architecture"),
        "os": inspected.get("Os"),
    }


def windows_to_wsl(path: Path) -> str:
    resolved = path.resolve()
    drive = resolved.drive.rstrip(":").lower()
    if len(drive) != 1 or not drive.isalpha():
        raise ValueError(f"expected a drive-qualified Windows path, got {resolved}")
    tail = "/".join(resolved.parts[1:]).replace("\\", "/")
    return f"/mnt/{drive}/{tail}"


def wsl_runtime_metadata(distro: str) -> dict[str, Any]:
    environment = dict(os.environ)
    environment["WSL_UTF8"] = "1"

    def capture(*command: str) -> str:
        completed = subprocess.run(
            ["wsl", "-d", distro, "-u", "root", "--", *command],
            check=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            env=environment,
        )
        return completed.stdout.strip()

    return {
        "distribution": distro,
        "os_release": capture("cat", "/etc/os-release"),
        "sage_version": capture("sage", "--version"),
        "sagemath_package": capture(
            "dpkg-query", "--show", "sagemath", "python3-sage"
        ),
        "python": capture("python3", "--version"),
        "wsl_version": subprocess.run(
            ["wsl", "--version"],
            capture_output=True,
            check=True,
            env=environment,
        ).stdout.decode("utf-8").strip(),
    }


def parse_rop_exponents(stdout: str) -> dict[str, Any]:
    current: str | None = None
    models: dict[str, dict[str, float]] = {}
    pattern = re.compile(r"^ATTACK\s+(\S+)\s+::.*?rop:\s*(?:≈|~)?2\^(-?[0-9.]+)")
    for line in stdout.splitlines():
        if line.startswith("MODEL_BEGIN "):
            current = line.split(maxsplit=1)[1]
            models[current] = {}
            continue
        match = pattern.search(line)
        if current and match:
            models[current][match.group(1)] = float(match.group(2))
    return {
        model: {
            "rop_log2_by_attack": attacks,
            "minimum_rop_log2": min(attacks.values()) if attacks else None,
        }
        for model, attacks in models.items()
    }


def run(args: argparse.Namespace) -> dict[str, Any]:
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    estimator_dir = args.estimator_dir.resolve()
    commit = git_commit(estimator_dir)
    if commit != EXPECTED_ESTIMATOR_COMMIT and not args.allow_estimator_commit_mismatch:
        raise RuntimeError(
            f"estimator commit {commit} != pinned {EXPECTED_ESTIMATOR_COMMIT}"
        )
    parameters = extract_parameters()
    program = sage_program(parameters, args.profile)
    sage_path = output_dir / f"lwe_estimator_{args.profile}.sage"
    sage_path.write_text(program, encoding="utf-8", newline="\n")

    package_binary = Path(ts.__file__).resolve().parent.parent / (
        "_tenseal_cpp.cp311-win_amd64.pyd"
    )
    record: dict[str, Any] = {
        "schema": SCHEMA,
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "parameters": parameters,
        "estimator": {
            "repository": "https://github.com/malb/lattice-estimator",
            "commit": commit,
            "profile": args.profile,
            "sage_input": sage_path.name,
            "sage_input_sha256": sha256_bytes(program.encode("utf-8")),
            "status": "input_archived_not_executed",
        },
        "implementation": {
            "tenseal_version": getattr(ts, "__version__", "unknown"),
            "tenseal_binary": str(package_binary),
            "tenseal_binary_sha256": (
                sha256_file(package_binary) if package_binary.exists() else None
            ),
            "microsoft_seal_version": SEAL_VERSION,
            "microsoft_seal_source_commit": SEAL_SOURCE_COMMIT,
            "parameter_extraction_api": "tenseal.sealapi.CoeffModulus.Create",
        },
        "scope": {
            "established": [
                "exact key-context modulus extracted through the implementation API",
                "pinned reproducible estimator input for the stated LWE models",
            ],
            "not_established": [
                "formal reduction from the full CKKS implementation to plain LWE",
                "circular/KDM security of Galois evaluation keys",
                "circuit privacy or q-IND-CPA-D security",
                "malicious-client security",
            ],
        },
        "software": {
            "python": platform.python_version(),
            "platform": platform.platform(),
        },
    }

    if args.run_estimator:
        if args.execution_backend == "docker":
            record["estimator"]["runtime"] = {
                "kind": "docker",
                **docker_image_metadata(args.docker_image),
            }
            container_name = f"ckks-lwe-estimator-{args.profile}"
            command = [
                "docker",
                "run",
                "--rm",
                "--name",
                container_name,
                "-e",
                "PYTHONUNBUFFERED=1",
                "-e",
                "PYTHONPATH=/estimator",
                "-v",
                f"{estimator_dir}:/estimator:ro",
                "-v",
                f"{output_dir}:/output",
                "-w",
                "/estimator",
                args.docker_image,
                "sage",
                f"/output/{sage_path.name}",
            ]
            stop_command = ["docker", "stop", "--time", "0", container_name]
        else:
            record["estimator"]["runtime"] = {
                "kind": "wsl",
                **wsl_runtime_metadata(args.wsl_distro),
            }
            estimator_wsl = windows_to_wsl(estimator_dir)
            sage_wsl = windows_to_wsl(sage_path)
            command = [
                "wsl",
                "-d",
                args.wsl_distro,
                "-u",
                "root",
                "--cd",
                estimator_wsl,
                "--",
                "env",
                "PYTHONUNBUFFERED=1",
                f"PYTHONPATH={estimator_wsl}",
                "sage",
                sage_wsl,
            ]
            stop_command = ["wsl", "--terminate", args.wsl_distro]
        stdout_path = output_dir / f"lwe_estimator_{args.profile}_stdout.txt"
        stderr_path = output_dir / f"lwe_estimator_{args.profile}_stderr.txt"
        estimator_started = time.perf_counter()
        timed_out = False
        with stdout_path.open("w", encoding="utf-8", newline="\n") as stdout_stream, (
            stderr_path.open("w", encoding="utf-8", newline="\n")
        ) as stderr_stream:
            process = subprocess.Popen(
                command,
                stdout=stdout_stream,
                stderr=stderr_stream,
                text=True,
                encoding="utf-8",
                errors="replace",
                env={**os.environ, "WSL_UTF8": "1"},
            )
            try:
                return_code = process.wait(timeout=args.estimator_timeout_seconds)
            except subprocess.TimeoutExpired:
                timed_out = True
                process.kill()
                process.wait()
                subprocess.run(
                    stop_command,
                    capture_output=True,
                    text=True,
                )
                return_code = 124
        estimator_elapsed = time.perf_counter() - estimator_started
        stdout = stdout_path.read_text(encoding="utf-8")
        stderr = stderr_path.read_text(encoding="utf-8")
        status = (
            "timed_out_partial_output_archived"
            if timed_out
            else ("completed" if return_code == 0 else "failed")
        )
        record["estimator"].update(
            {
                "command": command,
                "exit_code": return_code,
                "elapsed_seconds": estimator_elapsed,
                "timeout_seconds": args.estimator_timeout_seconds,
                "stdout": stdout_path.name,
                "stdout_sha256": sha256_bytes(stdout.encode("utf-8")),
                "stderr": stderr_path.name,
                "stderr_sha256": sha256_bytes(stderr.encode("utf-8")),
                "status": status,
                "parsed_costs": parse_rop_exponents(stdout),
            }
        )

    (output_dir / "security_parameters.json").write_text(
        json.dumps(record, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return record


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimator-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--profile", choices=["rough", "extended"], default="rough")
    parser.add_argument("--run-estimator", action="store_true")
    parser.add_argument(
        "--execution-backend", choices=["docker", "wsl"], default="docker"
    )
    parser.add_argument("--docker-image", default="sagemath/sagemath:10.6")
    parser.add_argument("--wsl-distro", default="CodexSageEstimator")
    parser.add_argument("--estimator-timeout-seconds", type=float)
    parser.add_argument("--allow-estimator-commit-mismatch", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    record = run(args)
    print(
        json.dumps(
            {
                "status": record["estimator"]["status"],
                "commit": record["estimator"]["commit"],
                "q_bits": record["parameters"]["total_coeff_modulus_bits"],
                "seal_tc128_max_bits": record["parameters"][
                    "seal_tc128_max_coeff_modulus_bits"
                ],
            }
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
