"""Regenerate the JISA review source from the canonical article source.

The scientific body and bibliography live in ``../paper/paper_en.tex``.
This script only replaces the document-class/front-matter wrapper and copies
the figures referenced by the current body.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path


HERE = Path(__file__).resolve().parent
CANONICAL = HERE.parent / "paper" / "paper_en.tex"
FIGURE_SOURCE = HERE.parent / "paper" / "figs"
TITLE = "SHARD: cell-keyed residual splitting for alignment-resistant private dense retrieval"


def between(text: str, start: str, end: str) -> str:
    return text.split(start, 1)[1].split(end, 1)[0]


def main() -> None:
    source = CANONICAL.read_text(encoding="utf-8").replace("\r\n", "\n")
    expected = (
        r"\title{\textbf{SHARD: cell-keyed residual splitting for"
        "\nalignment-resistant private dense retrieval}}"
    )
    if expected not in source:
        raise RuntimeError("Canonical title changed; update the JISA wrapper deliberately.")

    abstract = between(source, r"\begin{abstract}", r"\end{abstract}").strip()
    abstract = re.sub(r"^\\noindent\s*", "", abstract)
    keyword_match = re.search(r"\\textbf\{Keywords:\}\s*(.*?)\n\n", source, re.S)
    if not keyword_match:
        raise RuntimeError("Could not locate canonical keywords.")
    keywords = " ".join(keyword_match.group(1).split()).rstrip(".")
    keyword_tex = " \\sep\n".join(part.strip() for part in keywords.split(","))

    body_start = source.index(r"\section{Introduction}")
    bibliography_start = source.index(r"\begin{thebibliography}")
    bibliography_end = source.index(r"\end{thebibliography}") + len(
        r"\end{thebibliography}"
    )
    body = source[body_start:bibliography_start].rstrip() + "\n"
    # The review class is narrower and double-spaced. Keep the scientific
    # source identical while making floats fit the JISA review layout.
    body = re.sub(
        r"(\\begin\{tabular\}.*?\\end\{tabular\})",
        r"\\begin{adjustbox}{max width=\\linewidth}\n\1\n\\end{adjustbox}",
        body,
        flags=re.S,
    )
    body = re.sub(
        r"(\\begin\{tikzpicture\}.*?\\end\{tikzpicture\})",
        r"\\begin{adjustbox}{max width=\\linewidth}\n\1\n\\end{adjustbox}",
        body,
        flags=re.S,
    )
    body = re.sub(
        r"(\\begin\{table\}(?:\[[^]]*\])?)",
        r"\1\n\\begin{singlespace}",
        body,
    )
    body = body.replace(r"\end{table}", "\\end{singlespace}\n\\end{table}")
    references = source[bibliography_start:bibliography_end].rstrip() + "\n"

    wrapper = rf"""%% Submission to Elsevier, Journal of Information Security and Applications (JISA)
%% Generated by sync_from_canonical.py from ../paper/paper_en.tex.
\documentclass[review]{{elsarticle}}

\usepackage[T1]{{fontenc}}
\usepackage[utf8]{{inputenc}}
\usepackage[english]{{babel}}
\usepackage{{amsmath,amssymb,amsthm}}
\usepackage{{graphicx}}
\usepackage{{tikz}}
\usetikzlibrary{{arrows.meta,positioning}}
\usepackage{{booktabs,multirow,longtable,array}}
\usepackage{{microtype,xcolor}}
\usepackage{{enumitem,placeins,float}}
\usepackage{{adjustbox,setspace}}
\usepackage{{caption}}
\usepackage[hidelinks,colorlinks=false]{{hyperref}}

\captionsetup[table]{{skip=4pt,labelfont=bf}}
\captionsetup[figure]{{skip=4pt,labelfont=bf}}
\setcounter{{topnumber}}{{4}}
\setcounter{{bottomnumber}}{{2}}
\setcounter{{totalnumber}}{{6}}
\renewcommand{{\topfraction}}{{0.92}}
\renewcommand{{\bottomfraction}}{{0.85}}
\renewcommand{{\textfraction}}{{0.06}}
\renewcommand{{\floatpagefraction}}{{0.65}}
\graphicspath{{{{./}}}}
\emergencystretch=3em

\newtheorem{{proposition}}{{Proposition}}
\newtheorem{{hypothesis}}{{Empirical Hypothesis}}
\newtheorem{{corollary}}{{Corollary}}

\journal{{Journal of Information Security and Applications}}

\begin{{document}}
\begin{{frontmatter}}

\title{{{TITLE}}}
\author{{Sergey Kurilenko}}
\address{{Moscow Institute of Physics and Technology (MIPT),
Dolgoprudny 141701, Russia}}
\ead{{sergkurilenko@gmail.com}}

\begin{{abstract}}
{abstract}
\end{{abstract}}

\begin{{keyword}}
{keyword_tex}
\end{{keyword}}

\end{{frontmatter}}

\input{{body.tex}}
\input{{refs.tex}}

\end{{document}}
"""

    (HERE / "body.tex").write_text(body, encoding="utf-8", newline="\n")
    (HERE / "refs.tex").write_text(references, encoding="utf-8", newline="\n")
    (HERE / "paper_jisa.tex").write_text(wrapper, encoding="utf-8", newline="\n")

    graphics = re.findall(r"\\includegraphics(?:\[[^]]*\])?\{([^}]+)\}", body)
    missing: list[str] = []
    for name in sorted(set(graphics)):
        candidate = FIGURE_SOURCE / name
        if not candidate.exists():
            missing.append(name)
            continue
        shutil.copy2(candidate, HERE / Path(name).name)
    if missing:
        raise FileNotFoundError(f"Missing canonical figures: {missing}")

    print(f"Synchronized {len(body.splitlines())} body lines and {len(set(graphics))} figures.")


if __name__ == "__main__":
    main()
